version: '3.3'
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '80:80'
  #     - '443:443'
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      FLASK_APP: backend/server.py
    ports:
      - '80:8000'